# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016' # Ubuntu 16.04 cannot be used until GitVersion has support for Ubuntu (https://github.com/GitTools/GitVersion/issues/1542)
  
variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.2.101'
  inputs:
    version: 2.2.101

- task: GitVersion@4
  inputs:
    updateAssemblyInfo: true

- script: |
    dotnet build --configuration $(buildConfiguration) /p:AssemblyVersion=$(GitVersion.AssemblySemVer);FileVersion=$(GitVersion.AssemblySemVer);InformationalVersion=$(GitVersion.InformationalVersion)
    dotnet test --no-build --configuration $(buildConfiguration) --logger trx --collect "Code coverage"
    dotnet pack "**/Reynj.csproj" --no-build --configuration $(buildConfiguration) --include-symbols -p:PackageVersion=$(GitVersion.NuGetVersion) --output "$(Build.ArtifactStagingDirectory)"

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1