# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016' # Ubuntu 16.04 cannot be used until GitVersion has support for Ubuntu (https://github.com/GitTools/GitVersion/issues/1542)
  
variables:
  buildConfiguration: 'Release'

trigger:
  batch: false
  branches:
    include:
    - master
    - refs/tags/*

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.2.102'
  inputs:
    version: 2.2.102

- task: GitVersion@4
  inputs:
    updateAssemblyInfo: false

- script: dotnet build --configuration $(buildConfiguration) /p:AssemblyVersion=$(GitVersion.AssemblySemVer);FileVersion=$(GitVersion.AssemblySemVer);InformationalVersion=$(GitVersion.InformationalVersion)

- script: dotnet test --no-build --configuration $(buildConfiguration) --logger trx --collect "Code coverage"

- script: dotnet pack --no-build --configuration $(buildConfiguration) --include-symbols -p:PackageVersion=$(GitVersion.NuGetVersion) --output "$(Build.ArtifactStagingDirectory)"

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1