# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016' # Ubuntu 16.04 cannot be used until GitVersion has support for Ubuntu (https://github.com/GitTools/GitVersion/issues/1542)
  
variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.2.101'
  inputs:
    version: 2.2.101

- task: GitVersion@4
  inputs:
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    arguments: '/p:AssemblyVersion=$(GitVersion.AssemblySemVer);FileVersion=$(GitVersion.AssemblySemVer);InformationalVersion=$(GitVersion.InformationalVersion)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    nobuild: true
    arguments: '--collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    nobuild: true
    packagesToPack: '**/Reynj.csproj'
    arguments: '--include-symbols -p:PackageVersion=$(GitVersion.NuGetVersion)'

- task: PublishBuildArtifacts@1