trigger:
  batch: false
  branches:
    include:
    - master
    - refs/tags/*

stages:
- stage: 'Build'
  variables:
    buildConfiguration: 'Release'

  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: gitversion/setup@0
      displayName: 'Install GitVersion'
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: 'Determine application version with GitVersion'

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 2.1.x'
      inputs:
        packageType: sdk
        version: 2.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.1.x'
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 5.0.x'
      inputs:
        packageType: sdk
        version: 5.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 6.0.x'
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: 'Build Project'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) /p:AssemblyVersion=$(GitVersion.AssemblySemVer);FileVersion=$(GitVersion.AssemblySemVer);InformationalVersion=$(GitVersion.InformationalVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Test Project'
      inputs:
        command: test
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Project'
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj;!**/*Tests.csproj'
        outputDir: '$(Build.ArtifactStagingDirectory)/packages'
        configuration: '$(buildConfiguration)'
        nobuild: true
        includesymbols: true
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'GitVersion.NuGetVersion'

    - publish: '$(Build.ArtifactStagingDirectory)/packages'
      artifact: 'packages'

- stage: 'Publish'
  dependsOn: 'Build'
  condition: succeeded()

  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'

    environment: 'NuGet'

    continueOnError: true

    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetCommand@2
            displayName: 'Push NuGet Package'
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/packages/*.nupkg;!$(Pipeline.Workspace)/packages/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'Reynj NuGet'