# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  solution: "**/*.sln"
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.2.101'
  inputs:
    version: 2.2.101

- task: GitVersion@4
  inputs:
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: "dotnet build"
  inputs:
    command: build
    arguments: "--configuration $(buildConfiguration) /p:AssemblyVersion=$(GitVersion.AssemblySemVer);FileVersion=$(GitVersion.AssemblySemVer);InformationalVersion=$(GitVersion.InformationalVersion)"

- task: DotNetCoreCLI@2
  displayName: "dotnet test"
  inputs:
    command: test
    arguments: "--configuration $(buildConfiguration) --logger:trx"

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: pack
    arguments: "--no-build --output nupkgs"

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TEST-*.trx'